### PR TITLE
Only attempt SSH upload on Yun boards

### PR DESCRIPTION
**Pull request by sandeepmistry**
Previously SSH uploads were attempted on Yun Shields if the HTTP method failed. However, this causes the following error on non-ATmega32u4 based boards:

```
merge-sketch-with-bootloader.lua /tmp/sketch.hex && /usr/bin/run-avrdude /tmp/sketch.hex
INFO[1635] Command finished with error: Process exited with: 1. Reason was:  () 
```

I think we should only be using SSH for the original Yun board.

### CODE REVIEW

**Comment by mastrolinux** [comment]
Can we pass a generic list of sshallowedboards instead of directly putting the board name in a piece of code? It will be hard to maintain. 

Good catch!

**Comment by sandeepmistry** [comment]
> Can we pass a generic list of sshallowedboards instead of directly putting the board name in a piece of code?

Good idea, which one of the following were you thinking of?

* Array in `programmer.go`
* Config. file entry in `config.ini`
* `sshallowedboards` parameter in the `/update` REST request
* Something else?

**Comment by sandeepmistry** [comment]
It might actually better for the client to specify SSH or HTTP instead of the current generic type of "network".

**Comment by mastrolinux** [comment]
array in programmer.go is fine for me. If it grows we can always move it to the config file in the future.

**Comment by sandeepmistry** [comment]
@mastrolinux array added in https://github.com/arduino/arduino-create-agent/pull/100/commits/f9da80c8cdd1edf224e9563e14a74b0c32059f9b

**Comment by sandeepmistry** [comment]
@facchinm does the Yun 101 have the same fqbn as the original Yun (`arduino:avr:yun`)?

**Comment by facchinm** [comment]
The Yun101 has `arduino:avr:yun101` as fqbn but keeps the same build variables of the original Yun (so code is 100% compatible except USB PID)

**Comment by zmoog** [comment]
This PR is obsolete, and the Yun 101 has never seen the light of the day. Closing. 

RIP.

**Pull request closed without merging**
