### PR TITLE
compile_webidebridge.sh: don't require all platforms compilers

### PR DESCRIPTION
**Pull request by xrmx**
So one can build the tool without preparing all cross compilers.

Signed-off-by: Riccardo Magliocchetti <riccardo.magliocchetti@gmail.com>

### CODE REVIEW

**Comment by mastrolinux** [comment]
nice, can you please add a ALL option to allow building for every platform quickly?
@xrmx

**Comment by xrmx** [comment]
Il 25/01/2016 13:03, Luca Cipriani ha scritto:
> nice, can you please add a ALL option to allow building for every platform quickly?

I don't think handling an "all" target in compilePlatform would be cleaner, i've 
updated the pull request moving the check inside compilePlatform and adding a 
wrapper that would compile every target. What do you think?

-- 
Riccardo Magliocchetti
@rmistaken

http://menodizero.it

**Comment by matteosuppo** [comment]
I'm afraid it wouldn't work for Linux ARM, because the command would become ```which 0```

**Comment by xrmx** [comment]
@matteosuppo nice catch! Anyway feel free to cherry-pick whatever you think is valuable in this pull request otherwise just close it.

**Comment by matteosuppo** [comment]
I'm closing it because we can now simply build it with go build, and the continuous integration server do not use compile_webidebridge.sh anymore.

**Pull request closed without merging**
