### PR TITLE
fix memory leak

### PR DESCRIPTION
**Pull request by thechampagne**
**Please check if the PR fulfills these requirements**

- [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-create-agent/pulls)
      before creating one)
- [ ] Tests for the changes have been added (for bug fixes / features)

* **What kind of change does this PR introduce?**

- **What is the current behavior?**

* **What is the new behavior?**

- **Does this PR introduce a breaking change?**

* **Other information**:

### CODE REVIEW

**Comment by umbynos** [comment]
Hello @thechampagne, thanks for your contribution! Could you please add a bit more context to this? It would make the review process a lot faster.
It seems that the CI is failing because [it cannot build on macos](https://github.com/arduino/arduino-create-agent/actions/runs/6293919479/job/17085066436?pr=837). Could you please take a look at it?

**Comment by umbynos** [comment]
Hello @thechampagne, one last thing, and I think we are ready to merge: could you please run `go fmt github.com/arduino/arduino-create-agent/certificates github.com/arduino/arduino-create-agent/systray`. It seems that the [CI is failing](https://github.com/arduino/arduino-create-agent/actions/runs/6298053987/job/17096189887?pr=837)

**Review by umbynos — APPROVED** [review]
Thanks a lot for your contribution!

**Review by ubidefeo — APPROVED** [review]
I have tested this on Mac OS Ventura.
The app is able to generate certificates once the password is correctly entered by the user.
(it prompts for it)

**Pull request merged**
