### PR TITLE
Add serial discovery support for m1 mac

### PR DESCRIPTION
**Pull request by umbynos**
**Please check if the PR fulfills these requirements**

- [X] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-create-agent/pulls)
      before creating one)
- [ ] Tests for the changes have been added (for bug fixes / features)

* **What kind of change does this PR introduce?**

feature

- **What is the current behavior?**

https://github.com/arduino/arduino-create-agent/issues/611
* **What is the new behavior?**

try to make an experimental build to support for mac m1
- **Does this PR introduce a breaking change?**

* **Other information**:

### CODE REVIEW

**Comment by parreirat** [comment]
Hello.

I have an M1, @ 11.2.1, and am trying to get my Elegoo MEGA2560 R3 board running for the first time.

I cannot see the device displayed on ports at all.
Arduino 1.8.13.

I was trying to compile this PR on both Rosetta terminal (where I get a segfault just installing Go), and on the regular terminal (e.g. M1), and can't build it either:

image

I'd love to help you out somehow if I could, testing this and whatnot, if that would be useful.

**Comment by umbynos** [comment]
Hi, thanks for your interest! I think the problem comes from the fact you are using https://github.com/bugst/go-serial/ version 1.1.1

Support for darwin amd64 was added in version 1.1.2 ([here](https://github.com/bugst/go-serial/commit/57b513a432c80124b080b60bc96992fb05cbb646))

**Comment by parreirat** [comment]
> Hi, thanks for your interest! I think the problem comes from the fact you are using https://github.com/bugst/go-serial/ version 1.1.1
> 
> Support for darwin amd64 was added in version 1.1.2 ([here](https://github.com/bugst/go-serial/commit/57b513a432c80124b080b60bc96992fb05cbb646)).
> 
> PS this PR is still a WIP, it's not ready yet. I think the board discovery still needs some work. The dep bump was only to use the correct version of the library with support for mac m1 (this library is used for the serial communication handling)

Hi! I got a different USB B cable today and seems that was the issue, it's working flawlessly now!

Thanks for your work! I'd be very happy to help with anything regarding M1 testing if you'd like :)

**Review by rsora — APPROVED** [review]
Excellent!

**Comment by umbynos** [comment]
Serial discovery should be working now on the M1 (still missing the tools)
image

**Pull request merged**
